/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Josh
 */
public class AdminGUI extends javax.swing.JFrame {


   /**
    * Creates new form GUI
    */
   public AdminGUI() {
      initComponents();
   }


   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {
      rightPanel = new javax.swing.JPanel();
      addUserButton = new javax.swing.JButton();
      addGroupButton = new javax.swing.JButton();
      userViewButton = new javax.swing.JButton();
      showTotalButton = new javax.swing.JButton();
      showGroupTotalButton = new javax.swing.JButton();
      showMessageTotalButton = new javax.swing.JButton();
      showPositivePercentageButton = new javax.swing.JButton();
      userName = new javax.swing.JTextField();
      groupName = new javax.swing.JTextField();
      nameTextField = new javax.swing.JTextField();
      groupTextField = new javax.swing.JTextField();
      jTextFieldUser = new javax.swing.JTextField();
      jTextFieldGroup = new javax.swing.JTextField();
      leftPanel = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTree1 = new javax.swing.JTree();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      addUserButton.setText("Add User");
      addUserButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addUserButtonActionPerformed(evt);
         }
      });

      addGroupButton.setText("Add Group");
      addGroupButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addGroupButtonActionPerformed(evt);
         }
      });

      userViewButton.setText("Open User View");
      userViewButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            userViewButtonActionPerformed(evt);
         }
      });

      showTotalButton.setText("Show User Total");

      showGroupTotalButton.setText("Show Messages Total");

      showMessageTotalButton.setText("Show Group Total");

      showPositivePercentageButton.setText("Show Positive Percentage");

      userName.setEditable(false);
      userName.setText("User Name: ");

      groupName.setEditable(false);
      groupName.setText("Group Name: ");

      jTextFieldUser.setEditable(false);
      jTextFieldUser.setText("Enter User Name:");

      jTextFieldGroup.setEditable(false);
      jTextFieldGroup.setText("Enter Group Name:");

      javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
      rightPanel.setLayout(rightPanelLayout);
      rightPanelLayout.setHorizontalGroup(
              rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(rightPanelLayout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addComponent(userViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addGroup(rightPanelLayout.createSequentialGroup()
                                              .addComponent(showTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                              .addComponent(showMessageTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addComponent(userName)
                                      .addComponent(groupName)
                                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                                              .addComponent(showGroupTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                              .addComponent(showPositivePercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGroup(rightPanelLayout.createSequentialGroup()
                                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jTextFieldUser)
                                                      .addComponent(jTextFieldGroup))
                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(groupTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                                      .addComponent(nameTextField))
                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(addGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                              .addContainerGap())
      );
      rightPanelLayout.setVerticalGroup(
              rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(rightPanelLayout.createSequentialGroup()
                              .addGap(12, 12, 12)
                              .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(groupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(addUserButton)
                                      .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(jTextFieldGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(groupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(addGroupButton))
                              .addGap(102, 102, 102)
                              .addComponent(userViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(showTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(showMessageTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(showPositivePercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(showGroupTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(406, 406, 406))
      );

      jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTree1MouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(jTree1);

      javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
      leftPanel.setLayout(leftPanelLayout);
      leftPanelLayout.setHorizontalGroup(
              leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
      );
      leftPanelLayout.setVerticalGroup(
              leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jScrollPane1)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addContainerGap())
      );
      layout.setVerticalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                      .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>

   /* This gets selected node text and displays it into jtext fields */
   private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {
      DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
      userName.setText("User Name: " + selectedNode.getUserObject().toString());
      if (selectedNode.getParent() != null) {
         groupName.setText("Group Name: " + selectedNode.getParent().toString());
      }
   }

   /* This adds a user to the tree */
   private void addUser(String name) {
      DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
      DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(name);
      selectedNode.add(newNode);

      // Reload jTree model
      DefaultTreeModel model = (DefaultTreeModel)jTree1.getModel();
      model.reload();
   }


   /* This opens the User GUI */
   private void userViewButtonActionPerformed(java.awt.event.ActionEvent evt) {
      UserGUI userGUI = new UserGUI();
      userGUI.setVisible(true);
   }

   String name;

   private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
      name = nameTextField.getText();
      nameTextField.setText("");
      if (name.isEmpty()){
         System.out.println("Name cannot be empty");
      } else {
         Driver.addUser(name);
      }

      DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
      DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(name);
      selectedNode.add(newNode);

      // reload jtree model
      DefaultTreeModel model = (DefaultTreeModel)jTree1.getModel();
      model.reload();
   }

   private void addGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {
      name = groupTextField.getText();
      groupTextField.setText("");
      if (name.isEmpty()){
         System.out.println("Name cannot be empty");
      } else {
         Driver.addGroup(name);
      }

      DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
      DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(name);
      selectedNode.add(newNode);

      // reload jtree model
      DefaultTreeModel model = (DefaultTreeModel)jTree1.getModel();
      model.reload();
   }

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new AdminGUI().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify
   private javax.swing.JButton addGroupButton;
   private javax.swing.JButton addUserButton;
   private javax.swing.JTextField groupName;
   private javax.swing.JTextField groupTextField;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextField jTextFieldUser;
   private javax.swing.JTextField jTextFieldGroup;
   private javax.swing.JTree jTree1;
   private javax.swing.JPanel leftPanel;
   private javax.swing.JTextField nameTextField;
   private javax.swing.JPanel rightPanel;
   private javax.swing.JButton showGroupTotalButton;
   private javax.swing.JButton showMessageTotalButton;
   private javax.swing.JButton showPositivePercentageButton;
   private javax.swing.JButton showTotalButton;
   private javax.swing.JTextField userName;
   private javax.swing.JButton userViewButton;
   // End of variables declaration
}
