/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Josh
 */
public class AdminGUI extends javax.swing.JFrame {

   /**
    * Creates new form GUI
    */
   public AdminGUI() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

      rightPanel = new javax.swing.JPanel();
      userId = new javax.swing.JTextArea();
      groupId = new javax.swing.JTextArea();
      addUserButton = new javax.swing.JButton();
      addGroupButton = new javax.swing.JButton();
      userViewButton = new javax.swing.JButton();
      showTotalButton = new javax.swing.JButton();
      showGroupTotalButton = new javax.swing.JButton();
      showMessageTotalButton = new javax.swing.JButton();
      showPositivePercentageButton = new javax.swing.JButton();
      leftPanel = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTree1 = new javax.swing.JTree();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      userId.setEditable(false);
      userId.setColumns(20);
      userId.setRows(5);
      userId.setText("User ID");

      groupId.setEditable(false);
      groupId.setColumns(20);
      groupId.setRows(5);
      groupId.setText("Group ID");
      groupId.setToolTipText("");

      addUserButton.setText("Add User");
      addUserButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addUserButtonActionPerformed(evt);
         }
      });

      addGroupButton.setText("Add Group");
      addGroupButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addGroupButtonActionPerformed(evt);
         }
      });

      userViewButton.setText("Open User View");
      userViewButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            userViewButtonActionPerformed(evt);
         }
      });

      showTotalButton.setText("Show User Total");

      showGroupTotalButton.setText("Show Messages Total");

      showMessageTotalButton.setText("Show Group Total");

      showPositivePercentageButton.setText("Show Positive Percentage");

      javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
      rightPanel.setLayout(rightPanelLayout);
      rightPanelLayout.setHorizontalGroup(
              rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(rightPanelLayout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addComponent(userViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addGroup(rightPanelLayout.createSequentialGroup()
                                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(userId, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                                      .addComponent(groupId))
                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(addGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                      .addGroup(rightPanelLayout.createSequentialGroup()
                                              .addComponent(showTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                              .addComponent(showMessageTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                                              .addGap(0, 0, Short.MAX_VALUE)
                                              .addComponent(showGroupTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                              .addComponent(showPositivePercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addContainerGap())
      );
      rightPanelLayout.setVerticalGroup(
              rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(rightPanelLayout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                      .addGroup(rightPanelLayout.createSequentialGroup()
                                              .addGap(1, 1, 1)
                                              .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                      .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                      .addComponent(groupId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(addGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18)
                              .addComponent(userViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(123, 123, 123)
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(showTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(showMessageTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(showPositivePercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(showGroupTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(406, 406, 406))
      );

      jScrollPane1.setViewportView(jTree1);

      javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
      leftPanel.setLayout(leftPanelLayout);
      leftPanelLayout.setHorizontalGroup(
              leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
      );
      leftPanelLayout.setVerticalGroup(
              leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jScrollPane1)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addContainerGap())
      );
      layout.setVerticalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                      .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>

   /* This opens the User GUI */
   private void userViewButtonActionPerformed(java.awt.event.ActionEvent evt) {
      UserGUI userGUI = new UserGUI();
      userGUI.setVisible(true);
   }

   private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
      EnterNameGUI enterNameGUI = new EnterNameGUI();
      enterNameGUI.setVisible(true);
   }

   private void addGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {
      EnterNameGUI enterNameGUI = new EnterNameGUI();
      enterNameGUI.setVisible(true);
   }

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new AdminGUI().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify
   private javax.swing.JButton addGroupButton;
   private javax.swing.JButton addUserButton;
   private javax.swing.JTextArea groupId;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTree jTree1;
   private javax.swing.JPanel leftPanel;
   private javax.swing.JPanel rightPanel;
   private javax.swing.JButton showGroupTotalButton;
   private javax.swing.JButton showMessageTotalButton;
   private javax.swing.JButton showPositivePercentageButton;
   private javax.swing.JButton showTotalButton;
   private javax.swing.JTextArea userId;
   private javax.swing.JButton userViewButton;
   // End of variables declaration
}
